export const countryPhoneCodes = [
  { iso: 'AFG', phoneCode: '+93', countryName: 'Afghanistan' },
  { iso: 'ALB', phoneCode: '+355', countryName: 'Albania' },
  { iso: 'DZA', phoneCode: '+213', countryName: 'Algeria' },
  { iso: 'AND', phoneCode: '+376', countryName: 'Andorra' },
  { iso: 'AGO', phoneCode: '+244', countryName: 'Angola' },
  { iso: 'AIA', phoneCode: '+1264', countryName: 'Anguilla' },
  { iso: 'ATG', phoneCode: '+1268', countryName: 'Antigua and Barbuda' },
  { iso: 'ARG', phoneCode: '+54', countryName: 'Argentina' },
  { iso: 'ARM', phoneCode: '+374', countryName: 'Armenia' },
  { iso: 'ABW', phoneCode: '+297', countryName: 'Aruba' },
  { iso: 'AUS', phoneCode: '+61', countryName: 'Australia' },
  { iso: 'AUT', phoneCode: '+43', countryName: 'Austria' },
  { iso: 'AZE', phoneCode: '+994', countryName: 'Azerbaijan' },
  { iso: 'BHS', phoneCode: '+1242', countryName: 'Bahamas' },
  { iso: 'BHR', phoneCode: '+973', countryName: 'Bahrain' },
  { iso: 'BGD', phoneCode: '+880', countryName: 'Bangladesh' },
  { iso: 'BRB', phoneCode: '+1246', countryName: 'Barbados' },
  { iso: 'BLR', phoneCode: '+375', countryName: 'Belarus' },
  { iso: 'BEL', phoneCode: '+32', countryName: 'Belgium' },
  { iso: 'BLZ', phoneCode: '+501', countryName: 'Belize' },
  { iso: 'BEN', phoneCode: '+229', countryName: 'Benin' },
  { iso: 'BMU', phoneCode: '+1441', countryName: 'Bermuda' },
  { iso: 'BTN', phoneCode: '+975', countryName: 'Bhutan' },
  { iso: 'BOL', phoneCode: '+591', countryName: 'Bolivia' },
  { iso: 'BIH', phoneCode: '+387', countryName: 'Bosnia and Herzegovina' },
  { iso: 'BWA', phoneCode: '+267', countryName: 'Botswana' },
  { iso: 'BRA', phoneCode: '+55', countryName: 'Brazil' },
  {
    iso: 'IOT',
    phoneCode: '+246',
    countryName: 'British Indian Ocean Territory',
  },
  { iso: 'VGB', phoneCode: '+1284', countryName: 'British Virgin Islands' },
  { iso: 'BRN', phoneCode: '+673', countryName: 'Brunei Darussalam' },
  { iso: 'BGR', phoneCode: '+359', countryName: 'Bulgaria' },
  { iso: 'BFA', phoneCode: '+226', countryName: 'Burkina Faso' },
  { iso: 'BDI', phoneCode: '+257', countryName: 'Burundi' },
  { iso: 'CPV', phoneCode: '+238', countryName: 'Cabo Verde' },
  { iso: 'KHM', phoneCode: '+855', countryName: 'Cambodia' },
  { iso: 'CMR', phoneCode: '+237', countryName: 'Cameroon' },
  { iso: 'CAN', phoneCode: '+1', countryName: 'Canada' },
  { iso: 'CYM', phoneCode: '+1345', countryName: 'Cayman Islands' },
  { iso: 'CAF', phoneCode: '+236', countryName: 'Central African Republic' },
  { iso: 'TCD', phoneCode: '+235', countryName: 'Chad' },
  { iso: 'CHL', phoneCode: '+56', countryName: 'Chile' },
  { iso: 'CHN', phoneCode: '+86', countryName: 'China' },
  { iso: 'COL', phoneCode: '+57', countryName: 'Colombia' },
  { iso: 'COM', phoneCode: '+269', countryName: 'Comoros' },
  { iso: 'COG', phoneCode: '+242', countryName: 'Congo' },
  { iso: 'COD', phoneCode: '+243', countryName: 'Congo (DRC)' },
  { iso: 'CRI', phoneCode: '+506', countryName: 'Costa Rica' },
  { iso: 'CIV', phoneCode: '+225', countryName: "Côte d'Ivoire" },
  { iso: 'HRV', phoneCode: '+385', countryName: 'Croatia' },
  { iso: 'CUB', phoneCode: '+53', countryName: 'Cuba' },
  { iso: 'CYP', phoneCode: '+357', countryName: 'Cyprus' },
  { iso: 'CZE', phoneCode: '+420', countryName: 'Czech Republic' },
  { iso: 'DNK', phoneCode: '+45', countryName: 'Denmark' },
  { iso: 'DJI', phoneCode: '+253', countryName: 'Djibouti' },
  { iso: 'DMA', phoneCode: '+1767', countryName: 'Dominica' },
  { iso: 'DOM', phoneCode: '+1', countryName: 'Dominican Republic' },
  { iso: 'ECU', phoneCode: '+593', countryName: 'Ecuador' },
  { iso: 'EGY', phoneCode: '+20', countryName: 'Egypt' },
  { iso: 'SLV', phoneCode: '+503', countryName: 'El Salvador' },
  { iso: 'GNQ', phoneCode: '+240', countryName: 'Equatorial Guinea' },
  { iso: 'ERI', phoneCode: '+291', countryName: 'Eritrea' },
  { iso: 'EST', phoneCode: '+372', countryName: 'Estonia' },
  { iso: 'SWZ', phoneCode: '+268', countryName: 'Eswatini' },
  { iso: 'ETH', phoneCode: '+251', countryName: 'Ethiopia' },
  { iso: 'FJI', phoneCode: '+679', countryName: 'Fiji' },
  { iso: 'FIN', phoneCode: '+358', countryName: 'Finland' },
  { iso: 'FRA', phoneCode: '+33', countryName: 'France' },
  { iso: 'GAB', phoneCode: '+241', countryName: 'Gabon' },
  { iso: 'GMB', phoneCode: '+220', countryName: 'Gambia' },
  { iso: 'GEO', phoneCode: '+995', countryName: 'Georgia' },
  { iso: 'DEU', phoneCode: '+49', countryName: 'Germany' },
  { iso: 'GHA', phoneCode: '+233', countryName: 'Ghana' },
  { iso: 'GIB', phoneCode: '+350', countryName: 'Gibraltar' },
  { iso: 'GRC', phoneCode: '+30', countryName: 'Greece' },
  { iso: 'GRL', phoneCode: '+299', countryName: 'Greenland' },
  { iso: 'GRD', phoneCode: '+1473', countryName: 'Grenada' },
  { iso: 'GUM', phoneCode: '+1671', countryName: 'Guam' },
  { iso: 'GTM', phoneCode: '+502', countryName: 'Guatemala' },
  { iso: 'GIN', phoneCode: '+224', countryName: 'Guinea' },
  { iso: 'GNB', phoneCode: '+245', countryName: 'Guinea-Bissau' },
  { iso: 'GUY', phoneCode: '+592', countryName: 'Guyana' },
  { iso: 'HTI', phoneCode: '+509', countryName: 'Haiti' },
  { iso: 'HND', phoneCode: '+504', countryName: 'Honduras' },
  { iso: 'HKG', phoneCode: '+852', countryName: 'Hong Kong' },
  { iso: 'HUN', phoneCode: '+36', countryName: 'Hungary' },
  { iso: 'ISL', phoneCode: '+354', countryName: 'Iceland' },
  { iso: 'IND', phoneCode: '+91', countryName: 'India' },
  { iso: 'IDN', phoneCode: '+62', countryName: 'Indonesia' },
  { iso: 'IRN', phoneCode: '+98', countryName: 'Iran' },
  { iso: 'IRQ', phoneCode: '+964', countryName: 'Iraq' },
  { iso: 'IRL', phoneCode: '+353', countryName: 'Ireland' },
  { iso: 'ISR', phoneCode: '+972', countryName: 'Israel' },
  { iso: 'ITA', phoneCode: '+39', countryName: 'Italy' },
  { iso: 'JAM', phoneCode: '+1876', countryName: 'Jamaica' },
  { iso: 'JPN', phoneCode: '+81', countryName: 'Japan' },
  { iso: 'JOR', phoneCode: '+962', countryName: 'Jordan' },
  { iso: 'KAZ', phoneCode: '+7', countryName: 'Kazakhstan' },
  { iso: 'KEN', phoneCode: '+254', countryName: 'Kenya' },
  { iso: 'KIR', phoneCode: '+686', countryName: 'Kiribati' },
  { iso: 'PRK', phoneCode: '+850', countryName: 'Korea (DPRK)' },
  { iso: 'KOR', phoneCode: '+82', countryName: 'Korea (South)' },
  { iso: 'KWT', phoneCode: '+965', countryName: 'Kuwait' },
  { iso: 'KGZ', phoneCode: '+996', countryName: 'Kyrgyzstan' },
  { iso: 'LAO', phoneCode: '+856', countryName: 'Lao PDR' },
  { iso: 'LVA', phoneCode: '+371', countryName: 'Latvia' },
  { iso: 'LBN', phoneCode: '+961', countryName: 'Lebanon' },
  { iso: 'LSO', phoneCode: '+266', countryName: 'Lesotho' },
  { iso: 'LBR', phoneCode: '+231', countryName: 'Liberia' },
  { iso: 'LBY', phoneCode: '+218', countryName: 'Libya' },
  { iso: 'LIE', phoneCode: '+423', countryName: 'Liechtenstein' },
  { iso: 'LTU', phoneCode: '+370', countryName: 'Lithuania' },
  { iso: 'LUX', phoneCode: '+352', countryName: 'Luxembourg' },
  { iso: 'MAC', phoneCode: '+853', countryName: 'Macao' },
  { iso: 'MDG', phoneCode: '+261', countryName: 'Madagascar' },
  { iso: 'MWI', phoneCode: '+265', countryName: 'Malawi' },
  { iso: 'MYS', phoneCode: '+60', countryName: 'Malaysia' },
  { iso: 'MDV', phoneCode: '+960', countryName: 'Maldives' },
  { iso: 'MLI', phoneCode: '+223', countryName: 'Mali' },
  { iso: 'MLT', phoneCode: '+356', countryName: 'Malta' },
  { iso: 'MHL', phoneCode: '+692', countryName: 'Marshall Islands' },
  { iso: 'MRT', phoneCode: '+222', countryName: 'Mauritania' },
  { iso: 'MUS', phoneCode: '+230', countryName: 'Mauritius' },
  { iso: 'MEX', phoneCode: '+52', countryName: 'Mexico' },
  { iso: 'FSM', phoneCode: '+691', countryName: 'Micronesia' },
  { iso: 'MDA', phoneCode: '+373', countryName: 'Moldova' },
  { iso: 'MCO', phoneCode: '+377', countryName: 'Monaco' },
  { iso: 'MNG', phoneCode: '+976', countryName: 'Mongolia' },
  { iso: 'MNE', phoneCode: '+382', countryName: 'Montenegro' },
  { iso: 'MSR', phoneCode: '+1664', countryName: 'Montserrat' },
  { iso: 'MAR', phoneCode: '+212', countryName: 'Morocco' },
  { iso: 'MOZ', phoneCode: '+258', countryName: 'Mozambique' },
  { iso: 'MMR', phoneCode: '+95', countryName: 'Myanmar' },
  { iso: 'NAM', phoneCode: '+264', countryName: 'Namibia' },
  { iso: 'NRU', phoneCode: '+674', countryName: 'Nauru' },
  { iso: 'NPL', phoneCode: '+977', countryName: 'Nepal' },
  { iso: 'NLD', phoneCode: '+31', countryName: 'Netherlands' },
  { iso: 'NZL', phoneCode: '+64', countryName: 'New Zealand' },
  { iso: 'NIC', phoneCode: '+505', countryName: 'Nicaragua' },
  { iso: 'NER', phoneCode: '+227', countryName: 'Niger' },
  { iso: 'NGA', phoneCode: '+234', countryName: 'Nigeria' },
  { iso: 'NIU', phoneCode: '+683', countryName: 'Niue' },
  { iso: 'NFK', phoneCode: '+672', countryName: 'Norfolk Island' },
  { iso: 'MKD', phoneCode: '+389', countryName: 'North Macedonia' },
  { iso: 'NOR', phoneCode: '+47', countryName: 'Norway' },
  { iso: 'OMN', phoneCode: '+968', countryName: 'Oman' },
  { iso: 'PAK', phoneCode: '+92', countryName: 'Pakistan' },
  { iso: 'PLW', phoneCode: '+680', countryName: 'Palau' },
  { iso: 'PSE', phoneCode: '+970', countryName: 'Palestine, State of' },
  { iso: 'PAN', phoneCode: '+507', countryName: 'Panama' },
  { iso: 'PNG', phoneCode: '+675', countryName: 'Papua New Guinea' },
  { iso: 'PRY', phoneCode: '+595', countryName: 'Paraguay' },
  { iso: 'PER', phoneCode: '+51', countryName: 'Peru' },
  { iso: 'PHL', phoneCode: '+63', countryName: 'Philippines' },
  { iso: 'POL', phoneCode: '+48', countryName: 'Poland' },
  { iso: 'PRT', phoneCode: '+351', countryName: 'Portugal' },
  { iso: 'PRI', phoneCode: '+1', countryName: 'Puerto Rico' },
  { iso: 'QAT', phoneCode: '+974', countryName: 'Qatar' },
  { iso: 'ROU', phoneCode: '+40', countryName: 'Romania' },
  { iso: 'RUS', phoneCode: '+7', countryName: 'Russian Federation' },
  { iso: 'RWA', phoneCode: '+250', countryName: 'Rwanda' },
  { iso: 'SHN', phoneCode: '+290', countryName: 'Saint Helena' },
  { iso: 'KNA', phoneCode: '+1869', countryName: 'Saint Kitts and Nevis' },
  { iso: 'LCA', phoneCode: '+1758', countryName: 'Saint Lucia' },
  {
    iso: 'VCT',
    phoneCode: '+1784',
    countryName: 'Saint Vincent and the Grenadines',
  },
  { iso: 'WSM', phoneCode: '+685', countryName: 'Samoa' },
  { iso: 'SMR', phoneCode: '+378', countryName: 'San Marino' },
  { iso: 'STP', phoneCode: '+239', countryName: 'Sao Tome and Principe' },
  { iso: 'SAU', phoneCode: '+966', countryName: 'Saudi Arabia' },
  { iso: 'SEN', phoneCode: '+221', countryName: 'Senegal' },
  { iso: 'SRB', phoneCode: '+381', countryName: 'Serbia' },
  { iso: 'SYC', phoneCode: '+248', countryName: 'Seychelles' },
  { iso: 'SLE', phoneCode: '+232', countryName: 'Sierra Leone' },
  { iso: 'SGP', phoneCode: '+65', countryName: 'Singapore' },
  { iso: 'SVK', phoneCode: '+421', countryName: 'Slovakia' },
  { iso: 'SVN', phoneCode: '+386', countryName: 'Slovenia' },
  { iso: 'SLB', phoneCode: '+677', countryName: 'Solomon Islands' },
  { iso: 'SOM', phoneCode: '+252', countryName: 'Somalia' },
  { iso: 'ZAF', phoneCode: '+27', countryName: 'South Africa' },
  { iso: 'SSD', phoneCode: '+211', countryName: 'South Sudan' },
  { iso: 'ESP', phoneCode: '+34', countryName: 'Spain' },
  { iso: 'LKA', phoneCode: '+94', countryName: 'Sri Lanka' },
  { iso: 'SDN', phoneCode: '+249', countryName: 'Sudan' },
  { iso: 'SUR', phoneCode: '+597', countryName: 'Suriname' },
  { iso: 'SWE', phoneCode: '+46', countryName: 'Sweden' },
  { iso: 'CHE', phoneCode: '+41', countryName: 'Switzerland' },
  { iso: 'SYR', phoneCode: '+963', countryName: 'Syrian Arab Republic' },
  { iso: 'TWN', phoneCode: '+886', countryName: 'Taiwan' },
  { iso: 'TJK', phoneCode: '+992', countryName: 'Tajikistan' },
  { iso: 'TZA', phoneCode: '+255', countryName: 'Tanzania' },
  { iso: 'THA', phoneCode: '+66', countryName: 'Thailand' },
  { iso: 'TLS', phoneCode: '+670', countryName: 'Timor-Leste' },
  { iso: 'TGO', phoneCode: '+228', countryName: 'Togo' },
  { iso: 'TON', phoneCode: '+676', countryName: 'Tonga' },
  { iso: 'TTO', phoneCode: '+1868', countryName: 'Trinidad and Tobago' },
  { iso: 'TUN', phoneCode: '+216', countryName: 'Tunisia' },
  { iso: 'TUR', phoneCode: '+90', countryName: 'Turkey' },
  { iso: 'TKM', phoneCode: '+993', countryName: 'Turkmenistan' },
  { iso: 'TCA', phoneCode: '+1649', countryName: 'Turks and Caicos Islands' },
  { iso: 'TUV', phoneCode: '+688', countryName: 'Tuvalu' },
  { iso: 'UGA', phoneCode: '+256', countryName: 'Uganda' },
  { iso: 'UKR', phoneCode: '+380', countryName: 'Ukraine' },
  { iso: 'ARE', phoneCode: '+971', countryName: 'United Arab Emirates' },
  { iso: 'GBR', phoneCode: '+44', countryName: 'United Kingdom' },
  { iso: 'USA', phoneCode: '+1', countryName: 'United States of America' },
  { iso: 'URY', phoneCode: '+598', countryName: 'Uruguay' },
  { iso: 'UZB', phoneCode: '+998', countryName: 'Uzbekistan' },
  { iso: 'VUT', phoneCode: '+678', countryName: 'Vanuatu' },
  { iso: 'VEN', phoneCode: '+58', countryName: 'Venezuela' },
  { iso: 'VNM', phoneCode: '+84', countryName: 'Vietnam' },
  { iso: 'WLF', phoneCode: '+681', countryName: 'Wallis and Futuna' },
  { iso: 'ESH', phoneCode: '+212', countryName: 'Western Sahara' },
  { iso: 'YEM', phoneCode: '+967', countryName: 'Yemen' },
  { iso: 'ZMB', phoneCode: '+260', countryName: 'Zambia' },
  { iso: 'ZWE', phoneCode: '+263', countryName: 'Zimbabwe' },
];